### ISSUE TITLE
[DOC] Update README with npx example

### ISSUE THREAD

**Issue by bradtaniguchi** [nhcarrigan/gimme-colours#4]
# Incorrect Documentation

## Describe the error

There is a way to use this library by temporary install using `npx`.

## Expected information

An alternate example could include using `npx gimmie-colours` instead of the global install.

**Comment by nhcarrigan** [comment]
Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

A pull request that resolves this issue should:

- Update the `Usage` section of the `README.md` file:
  - Include instructions on installing the package locally with `npm i gimme-colours`
  - include instructions on using the local installation with `npx gimme-colours`

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, let us know and we can assign you to it. Please note that we typically accept the first PR to comprehensively resolve the issue (as long as it meets our contributing guidelines) regardless of who is assigned to an issue.

Happy contributing.

**Comment by Subhangini** [comment]
I would like to work on this issue.

**Comment by nhcarrigan** [comment]
I will assign you now. 🙂

**Comment by nhcarrigan** [comment]
No.

The existing global installation instructions are correct. We want to add an additional line below with the local installation instructions, ideally with a note that the global install is preferred.

**Comment by Subhangini** [comment]
ok ok

**Comment by Subhangini** [comment]
![S1](https://user-images.githubusercontent.com/68437435/110662176-44699580-81eb-11eb-96d6-043fb7c0f820.jpg)

Is it correct now?

**Comment by nhcarrigan** [comment]
Feel free to submit the PR and I will make any suggested changes there 🙂

**Comment by Subhangini** [comment]
There are some spelling mistakes .I will correct them other than that if something is wrong please tell me.
